#!/bin/sh
window_stack -vprint_prefix='getwindowgeometry --shell ' -vcurr_workspace=1 -vafter_active=1 -vskip_first=1 -vnum_windows=4 -vactive_first=1 | xdotool - | focus_direction.awk -vdirection="$1" | xdotool -
